# [DBKUTUPHANE]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [DBKUTUPHANE]    Script Date: 1.08.2024 11:12:11 ******/
CREATE DATABASE [DBKUTUPHANE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBKUTUPHANE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DBKUTUPHANE.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBKUTUPHANE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DBKUTUPHANE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [DBKUTUPHANE] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBKUTUPHANE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DBKUTUPHANE] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET ARITHABORT OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DBKUTUPHANE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DBKUTUPHANE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DBKUTUPHANE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DBKUTUPHANE] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DBKUTUPHANE] SET  MULTI_USER 
GO
ALTER DATABASE [DBKUTUPHANE] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DBKUTUPHANE] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DBKUTUPHANE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DBKUTUPHANE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DBKUTUPHANE] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DBKUTUPHANE] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [DBKUTUPHANE] SET QUERY_STORE = ON
GO
ALTER DATABASE [DBKUTUPHANE] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[TBLADMIN]

In [0]:
USE [DBKUTUPHANE]
GO

In [0]:
/****** Object:  Table [dbo].[TBLADMIN]    Script Date: 1.08.2024 11:12:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLADMIN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KULLANICI] [varchar](20) NULL,
	[SIFRE] [varchar](20) NULL,
 CONSTRAINT [PK_TBLADMIN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBLCEZALAR]

In [0]:
/****** Object:  Table [dbo].[TBLCEZALAR]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLCEZALAR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UYE] [int] NULL,
	[HAREKET] [int] NULL,
	[BASLANGIC_TARIHI] [smalldatetime] NULL,
	[BITIS_TARIHI] [smalldatetime] NULL,
	[PARA] [decimal](18, 2) NULL,
 CONSTRAINT [PK_TBLCEZALAR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBLDUYURULAR]

In [0]:
/****** Object:  Table [dbo].[TBLDUYURULAR]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLDUYURULAR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KATEGORI] [varchar](50) NULL,
	[ICERIK] [varchar](350) NULL,
	[TARIH] [smalldatetime] NULL,
 CONSTRAINT [PK_TBLDUYURULAR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBLHAKKIMIZDA]

In [0]:
/****** Object:  Table [dbo].[TBLHAKKIMIZDA]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLHAKKIMIZDA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ACIKLAMA] [varchar](max) NULL,
 CONSTRAINT [PK_TBLHAKKIMIZDA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[TBLHAREKET]

In [0]:
/****** Object:  Table [dbo].[TBLHAREKET]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLHAREKET](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KİTAP] [int] NULL,
	[UYE] [int] NULL,
	[PERSONEL] [int] NULL,
	[ALISTARIHI] [smalldatetime] NULL,
	[IADETARIHI] [smalldatetime] NULL,
	[ISLEMDURUM] [bit] NULL,
	[UYEGETIRTARIH] [smalldatetime] NULL,
 CONSTRAINT [PK_TBLHAREKET] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBLILETISIM]

In [0]:
/****** Object:  Table [dbo].[TBLILETISIM]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLILETISIM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NULL,
	[MAIL] [varchar](50) NULL,
	[KONU] [varchar](50) NULL,
	[MESAJ] [varchar](1000) NULL,
 CONSTRAINT [PK_TBLILETISIM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBLKASA]

In [0]:
/****** Object:  Table [dbo].[TBLKASA]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLKASA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AY] [varchar](20) NULL,
	[TUTAR] [decimal](18, 2) NULL,
 CONSTRAINT [PK_TBLKASA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBLKATEGORI]

In [0]:
/****** Object:  Table [dbo].[TBLKATEGORI]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLKATEGORI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ADI] [varchar](35) NULL,
	[DURUM] [bit] NULL,
 CONSTRAINT [PK_TBLKATEGORI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBLKITAP]

In [0]:
/****** Object:  Table [dbo].[TBLKITAP]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLKITAP](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NULL,
	[KATEGORI] [int] NULL,
	[YAZAR] [int] NULL,
	[BASIMYILI] [char](4) NULL,
	[YAYINEVI] [varchar](50) NULL,
	[SAYFASAYISI] [varchar](4) NULL,
	[DURUM] [bit] NULL,
	[KITAPRESIM] [varchar](350) NULL,
	[DURUM2] [bit] NULL,
 CONSTRAINT [PK_TBLKITAP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBLMESAJLAR]

In [0]:
/****** Object:  Table [dbo].[TBLMESAJLAR]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLMESAJLAR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GONDEREN] [varchar](50) NULL,
	[ALICI] [varchar](50) NULL,
	[KONU] [varchar](50) NULL,
	[ICERIK] [varchar](500) NULL,
	[TARIH] [smalldatetime] NULL,
 CONSTRAINT [PK_TBLMESAJLAR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBLPERSONEL]

In [0]:
/****** Object:  Table [dbo].[TBLPERSONEL]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLPERSONEL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PERSONEL] [varchar](50) NULL,
	[DURUM] [bit] NULL,
 CONSTRAINT [PK_TBLPERSONEL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBLUYELER]

In [0]:
/****** Object:  Table [dbo].[TBLUYELER]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLUYELER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ADI] [varchar](20) NULL,
	[SOYADI] [varchar](20) NULL,
	[MAIL] [varchar](50) NULL,
	[KULLANICIADI] [varchar](20) NULL,
	[SIFRE] [varchar](20) NULL,
	[FOTOGRAF] [varchar](300) NULL,
	[TELEFON] [varchar](20) NULL,
	[OKUL] [varchar](100) NULL,
	[DURUM] [bit] NULL,
 CONSTRAINT [PK_TBLUYELER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBLYAZAR]

In [0]:
/****** Object:  Table [dbo].[TBLYAZAR]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLYAZAR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](30) NULL,
	[SOYAD] [varchar](30) NULL,
	[DETAY] [varchar](1000) NULL,
	[DURUM] [bit] NULL,
 CONSTRAINT [PK_TBLYAZAR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [DF_TBLKITAP_DURUM]

In [0]:
ALTER TABLE [dbo].[TBLKITAP] ADD  CONSTRAINT [DF_TBLKITAP_DURUM]  DEFAULT ((1)) FOR [DURUM]
GO

# [FK_TBLCEZALAR_TBLHAREKET]

In [0]:
ALTER TABLE [dbo].[TBLCEZALAR]  WITH CHECK ADD  CONSTRAINT [FK_TBLCEZALAR_TBLHAREKET] FOREIGN KEY([HAREKET])
REFERENCES [dbo].[TBLHAREKET] ([ID])
GO
ALTER TABLE [dbo].[TBLCEZALAR] CHECK CONSTRAINT [FK_TBLCEZALAR_TBLHAREKET]
GO

# [FK_TBLCEZALAR_TBLUYELER]

In [0]:
ALTER TABLE [dbo].[TBLCEZALAR]  WITH CHECK ADD  CONSTRAINT [FK_TBLCEZALAR_TBLUYELER] FOREIGN KEY([UYE])
REFERENCES [dbo].[TBLUYELER] ([ID])
GO
ALTER TABLE [dbo].[TBLCEZALAR] CHECK CONSTRAINT [FK_TBLCEZALAR_TBLUYELER]
GO

# [FK_TBLHAREKET_TBLKITAP]

In [0]:
ALTER TABLE [dbo].[TBLHAREKET]  WITH CHECK ADD  CONSTRAINT [FK_TBLHAREKET_TBLKITAP] FOREIGN KEY([KİTAP])
REFERENCES [dbo].[TBLKITAP] ([ID])
GO
ALTER TABLE [dbo].[TBLHAREKET] CHECK CONSTRAINT [FK_TBLHAREKET_TBLKITAP]
GO

# [FK_TBLHAREKET_TBLPERSONEL]

In [0]:
ALTER TABLE [dbo].[TBLHAREKET]  WITH CHECK ADD  CONSTRAINT [FK_TBLHAREKET_TBLPERSONEL] FOREIGN KEY([PERSONEL])
REFERENCES [dbo].[TBLPERSONEL] ([ID])
GO
ALTER TABLE [dbo].[TBLHAREKET] CHECK CONSTRAINT [FK_TBLHAREKET_TBLPERSONEL]
GO

# [FK_TBLHAREKET_TBLUYELER]

In [0]:
ALTER TABLE [dbo].[TBLHAREKET]  WITH CHECK ADD  CONSTRAINT [FK_TBLHAREKET_TBLUYELER] FOREIGN KEY([UYE])
REFERENCES [dbo].[TBLUYELER] ([ID])
GO
ALTER TABLE [dbo].[TBLHAREKET] CHECK CONSTRAINT [FK_TBLHAREKET_TBLUYELER]
GO

# [FK_TBLKITAP_TBLKATEGORI]

In [0]:
ALTER TABLE [dbo].[TBLKITAP]  WITH CHECK ADD  CONSTRAINT [FK_TBLKITAP_TBLKATEGORI] FOREIGN KEY([KATEGORI])
REFERENCES [dbo].[TBLKATEGORI] ([ID])
GO
ALTER TABLE [dbo].[TBLKITAP] CHECK CONSTRAINT [FK_TBLKITAP_TBLKATEGORI]
GO

# [FK_TBLKITAP_TBLYAZAR]

In [0]:
ALTER TABLE [dbo].[TBLKITAP]  WITH CHECK ADD  CONSTRAINT [FK_TBLKITAP_TBLYAZAR] FOREIGN KEY([YAZAR])
REFERENCES [dbo].[TBLYAZAR] ([ID])
GO
ALTER TABLE [dbo].[TBLKITAP] CHECK CONSTRAINT [FK_TBLKITAP_TBLYAZAR]
GO

# [dbo].[EnAktifUye]

In [0]:
/****** Object:  StoredProcedure [dbo].[EnAktifUye]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EnAktifUye]
AS
SELECT TOP 1 TBLUYELER.ADI+TBLUYELER.SOYADI FROM TBLHAREKET
INNER JOIN TBLUYELER ON TBLUYELER.ID=TBLHAREKET.UYE
GROUP BY TBLUYELER.ADI,TBLUYELER.SOYADI ORDER BY COUNT(*) DESC
GO

# [dbo].[EnBasariliPersonel]

In [0]:
/****** Object:  StoredProcedure [dbo].[EnBasariliPersonel]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EnBasariliPersonel]
AS
SELECT TOP 1 TBLPERSONEL.PERSONEL FROM TBLHAREKET
INNER JOIN TBLPERSONEL ON TBLPERSONEL.ID=TBLHAREKET.PERSONEL 
WHERE  TBLHAREKET.ISLEMDURUM = 1
GROUP BY TBLPERSONEL.PERSONEL  ORDER BY COUNT(*) DESC 
GO

# [dbo].[EnCokOkunanKitapp]

In [0]:
/****** Object:  StoredProcedure [dbo].[EnCokOkunanKitapp]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EnCokOkunanKitapp]
AS
SELECT TOP 1 TBLKITAP.AD FROM TBLHAREKET
INNER JOIN TBLKITAP ON TBLKITAP.ID=TBLHAREKET.KİTAP
GROUP BY TBLKITAP.AD ORDER BY COUNT(*) DESC
GO

# [dbo].[EnFazlaKitapYazar]

In [0]:
/****** Object:  StoredProcedure [dbo].[EnFazlaKitapYazar]    Script Date: 1.08.2024 11:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EnFazlaKitapYazar]
AS
SELECT TOP 1 TBLYAZAR.AD+TBLYAZAR.SOYAD FROM TBLKITAP
INNER JOIN TBLYAZAR ON TBLYAZAR.ID=TBLKITAP.YAZAR
GROUP BY TBLYAZAR.AD,TBLYAZAR.SOYAD ORDER BY COUNT(*) DESC
GO

# [DBKUTUPHANE]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [DBKUTUPHANE] SET  READ_WRITE 
GO